# Generated by Django 5.1.6 on 2025-02-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='itinerary',
            field=models.TextField(blank=True, help_text='Detailed daily plan (use line breaks for each day)', null=True),
        ),
    ]
