# Generated by Django 5.1.6 on 2025-02-26 22:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_destination_faq_tourpackage_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='best_time_to_visit',
            field=models.CharField(default='Year-round', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='full_description',
            field=models.TextField(default='Description coming soon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.CharField(default='Bali', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='popular_activities',
            field=models.CharField(default='Trekking, Cultural Tours', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='destinations',
            field=models.ManyToManyField(related_name='tours', to='main.destination'),
        ),
    ]
